### ISSUE TITLE
Args with double dash is not recognized

### ISSUE THREAD

**Issue by fengxia41103** [purcell/sqlformat#12]
# Problem

Setting `sqlformat-args` w/ a double-dash option breaks the command execution.

# Steps

## pgformatter

If using `pgformatter` version 5.5:

```
(setq sqlformat-command 'pgformatter)
(setq sqlformat-args '("-s4" "-B" "-w80" "-k" "-f2" "-U2" "--extra-keyword ~/tmp/oracle-keywords))
```
Error:

```
Uncaught exception: Deadly warning: Unknown option: extra-keyword ~/workspace/tmp/oracle-keywords
 at /usr/local/bin/pg_format line 27.
	main::__ANON__("Unknown option: extra-keyword ~/workspace/tmp/oracle-keywords\x{a}") called at /usr/lib/x86_64-linux-gnu/perl-base/Getopt/Long.pm line 1074
	Getopt::Long::FindOption(ARRAY(0x55f2740efcf0), "(--|-|\\+)", "--", "--extra-keyword ~/workspace/tmp/oracle-keywords", HASH(0x55f274592b38)) called at /usr/lib/x86_64-linux-gnu/perl-base/Getopt/Long.pm line 529
	Getopt::Long::GetOptionsFromArray(undef, undef, undef, undef, undef, undef, undef, undef, ...) called at /usr/local/share/perl/5.34.0/pgFormatter/CLI.pm line 388
	pgFormatter::CLI::get_command_line_args(pgFormatter::CLI=HASH(0x55f2740c5890)) called at /usr/local/share/perl/5.34.0/pgFormatter/CLI.pm line 62
	pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55f2740c5890)) called at /usr/local/bin/pg_format line 49
 at /usr/local/bin/pg_format line 19.
	main::__ANON__("Deadly warning: Unknown option: extra-keyword ~/workspace/tmp"...) called at /usr/lib/x86_64-linux-gnu/perl-base/Carp.pm line 290
	Carp::confess("Deadly warning: Unknown option: extra-keyword ~/workspace/tmp"...) called at /usr/local/bin/pg_format line 27
	main::__ANON__("Unknown option: extra-keyword ~/workspace/tmp/oracle-keywords\x{a}") called at /usr/lib/x86_64-linux-gnu/perl-base/Getopt/Long.pm line 1074
	Getopt::Long::FindOption(ARRAY(0x55f2740efcf0), "(--|-|\\+)", "--", "--extra-keyword ~/workspace/tmp/oracle-keywords", HASH(0x55f274592b38)) called at /usr/lib/x86_64-linux-gnu/perl-base/Getopt/Long.pm line 529
	Getopt::Long::GetOptionsFromArray(undef, undef, undef, undef, undef, undef, undef, undef, ...) called at /usr/local/share/perl/5.34.0/pgFormatter/CLI.pm line 388
	pgFormatter::CLI::get_command_line_args(pgFormatter::CLI=HASH(0x55f2740c5890)) called at /usr/local/share/perl/5.34.0/pgFormatter/CLI.pm line 62
	pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55f2740c5890)) called at /usr/local/bin/pg_format line 49
```

## sqlformat

Similarly, sqlformat supports many args in double-dash format:

```
sqlformat -k upper -i upper -s --wrap_after 80 --indent_width 4 --indent_after_first
```
Executing in shell works. But setting in emacs doesn't.

```
(setq sqlformat-command 'sqlformat)
(setq sqlformat-args '("-k" "upper" "-i" "upper" "-s" "--wrap_after 80" "--indent_width" "4" "--indent_after_first"))
```

Error:

```
sqlformat: error: unrecognized arguments: -
```

# Expect

Not sure it's a documentation issue or code issue. I can't find in doc an example of using double-dash args. As seen in the `sqlformat` example above, I tried two different styles:

1. `"--wrap_after 80"`: all in one
2. `"--indent_width" "4"`: separated in two

I don't think it makes any difference since it's a LISP list, and should be passed onto to CLI as-is. But apparently neither worked.

**Comment by purcell** [comment]
This package isn't really doing anything fancy with the args. Is it possible that that the `sqlformat` executable visible to Emacs is not the same one that you see on the command line?

In the `pg_format` example, I'd expect that either of these should work:
```
(setq sqlformat-command 'pgformatter)
(setq sqlformat-args '("-s4" "-B" "-w80" "-k" "-f2" "-U2" "--extra-keyword=~/tmp/oracle-keywords"))
```
or
```
(setq sqlformat-command 'pgformatter)
(setq sqlformat-args '("-s4" "-B" "-w80" "-k" "-f2" "-U2" "--extra-keyword" "~/tmp/oracle-keywords"))
```
but note that the `~` might not get expanded by the command, so you might need to use the full path.

**Comment by fengxia41103** [comment]
I verified that for double-dash parameters, the key is using `--arg=<value>` format! This now works well w/ `sqlformat`.

```
(setq sqlformat-command 'sqlformat)
(setq sqlformat-args '("-k" "upper" "-i" "upper" "-s" "-r" "--indent_width=4" "--indent_after_first" "--strip-comments"))
```

If using `pg_format`, it will be nice to add an example of the `--extra-keyword` because it's not clear what the film format should be -- one keyword per line? CSV? For experiment, I have created a file with single word `TO_CHAR` in it. However, I couldn't tell any difference w/ or w/o this flag.

**Comment by purcell** [comment]
> I verified that for double-dash parameters, the key is using --arg=<value> format! 

This is actually the standard `getargs` behaviour: for almost all command-line programs it used to be that `-s 5` and `--some-opt=5` would work, but `-s=5` and `--some-opt 5` would not.

> If using pg_format, it will be nice to add an example of the --extra-keyword because it's not clear what the film format should be -- one keyword per line? CSV?

Documenting the args of specific formatters here is not the best plan IMO, and I'm not an expert on all of them anyway — if the usage of upstream programs is unclear, it's worth raising it with the maintainer.
